"""Create docs PR in target repository."""

import re

from github.Repository import Repository

from docnerd.doc_generator import DocEdit


def sanitize_branch_name(name: str) -> str:
    """Convert branch name to valid git ref (replace / with -)."""
    return re.sub(r"[^a-zA-Z0-9\-_.]", "-", name)


def make_work_branch_name(source_pr_number: int, target_branch: str, prefix: str = "docnerd") -> str:
    """Create branch name for docNerd's working branch."""
    safe_target = sanitize_branch_name(target_branch)
    return f"{prefix}/{source_pr_number}-{safe_target}"


def find_existing_docs_pr(
    repo: Repository,
    source_pr_number: int,
    target_branch: str,
    branch_prefix: str = "docnerd",
) -> str | None:
    """
    Find an existing docs PR for this source PR + target branch.
    Returns PR HTML URL if found, else None.
    """
    safe_target = sanitize_branch_name(target_branch)
    search_head = f"{branch_prefix}/{source_pr_number}-{safe_target}"
    for pr in repo.get_pulls(state="open"):
        if pr.head.ref == search_head:
            return pr.html_url
    return None


def create_docs_pr(
    repo: Repository,
    target_branch: str,
    source_pr_number: int,
    source_pr_url: str,
    source_pr_title: str,
    edits: list[DocEdit],
    branch_prefix: str = "docnerd",
    token: str | None = None,
) -> str:
    """
    Create a branch, apply doc edits, and open a PR in the docs repo.

    Args:
        repo: Target docs repository
        target_branch: Branch to target (e.g. core/v7.1)
        source_pr_number: Source PR number
        source_pr_url: Source PR URL
        source_pr_title: Source PR title
        edits: List of DocEdit from doc generator
        branch_prefix: Prefix for work branches
        token: Optional token (if repo was created with different token)

    Returns:
        HTML URL of the created PR
    """
    work_branch = make_work_branch_name(source_pr_number, target_branch, branch_prefix)

    # Get base branch SHA
    base_ref = repo.get_git_ref(f"heads/{target_branch}")
    base_sha = base_ref.object.sha

    # Create work branch
    try:
        repo.create_git_ref(f"refs/heads/{work_branch}", base_sha)
    except Exception as e:
        if "Reference already exists" in str(e):
            # Branch exists - return existing PR if open, else force-reset to base
            existing = find_existing_docs_pr(repo, source_pr_number, target_branch, branch_prefix)
            if existing:
                return existing
            # Force-reset branch to base (allows non-fast-forward when branch has diverged)
            ref = repo.get_git_ref(f"heads/{work_branch}")
            ref.edit(base_sha, force=True)
        else:
            raise

    # Apply edits
    for edit in edits:
        path = edit.path
        content = edit.content
        try:
            existing = repo.get_contents(path, ref=work_branch)
            repo.update_file(
                path,
                f"docs: update for source PR #{source_pr_number}",
                content,
                existing.sha,
                branch=work_branch,
            )
        except Exception:
            # File doesn't exist, create it
            repo.create_file(
                path,
                f"docs: add for source PR #{source_pr_number}",
                content,
                branch=work_branch,
            )

    # Create PR (or return existing)
    existing_url = find_existing_docs_pr(repo, source_pr_number, target_branch, branch_prefix)
    if existing_url:
        return existing_url

    pr_title = f"Docs: {source_pr_title}"
    pr_body = f"""Documentation updates for [{source_pr_title}]({source_pr_url}) (#{source_pr_number}).

Generated by docNerd.
"""
    pr = repo.create_pull(
        title=pr_title,
        body=pr_body,
        head=work_branch,
        base=target_branch,
    )

    return pr.html_url
